---
- name: Converge
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
  - include_tasks: tasks/user.yml

  - include_tasks: tasks/python_virtualenv.yml

  - include_tasks: tasks/install_git.yml

  - include_tasks: tasks/install_AutoRecon.yml
  - include_tasks: tasks/install_chisel.yml
  - include_tasks: tasks/install_evil-winrm.yml
  - include_tasks: tasks/install_gobuster.yml
  - include_tasks: tasks/install_gcc-multilib.yml
  - include_tasks: tasks/install_LinEnum.yml
  - include_tasks: tasks/install_nishang.yml
  - include_tasks: tasks/install_one-lin3r.yml
  - include_tasks: tasks/install_OSCP_report_templates.yml
  - include_tasks: tasks/install_pspy.yml
  - include_tasks: tasks/install_PowerSploit.yml
  - include_tasks: tasks/install_powerless.yml
  - include_tasks: tasks/install_proxychains-ng.yml
  - include_tasks: tasks/install_payloadsallthethings.yml
  - include_tasks: tasks/install_SecLists.yml
  - include_tasks: tasks/install_sherlock.yml
  - include_tasks: tasks/install_sshuttle.yml
  - include_tasks: tasks/install_webshell.yml
  - include_tasks: tasks/install_wkhtmltopdf.yml
  - include_tasks: tasks/install_xsstrike.yml
  - include_tasks: tasks/install_GEF.yml
  - include_tasks: tasks/install_pwntools.yml
  - include_tasks: tasks/update_polenum.yml

  - include_tasks: tasks/install_custom_samba_prereqs.yml
  - include_tasks: tasks/install_custom_samba.yml
  - include_tasks: tasks/install_nmap.yml

  - include_tasks: tasks/add_aliases.yml
