---
- name: Get igor_mukhin.bash_aliases
  command: ansible-galaxy install igor_mukhin.bash_aliases
  register: igor_mukhin
  changed_when: "'is already installed' not in igor_mukhin.stderr"
  failed_when: "'ERROR' in igor_mukhin.stderr"

- name: Include igor_mukhin.bash_aliases
  include_role:
    name: igor_mukhin.bash_aliases
  vars:
  - bash_aliases_path: "{{ homefolder + '.bash_aliases' }}"



