---
# https://github.com/danielmiessler/SecLists
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy SecLists from repository
  git:
    repo: "https://github.com/danielmiessler/SecLists.git"
    dest: "/usr/share/seclists/"
    update: yes
